name: Tests CI/CD

on: ["push"]

env:
 DATABASE_NAME: "test"

jobs:
  dummy-job:
    strategy:
      matrix:
        version: [14, 16, 18]
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    name: "my job"
    runs-on:  ${{matrix.os}}
    steps:
      - run: ls -la
        if: ${{runner.os == 'linux'|| runner.os == 'macos'}}
      - run: dir
        if: ${{runner.os == 'windows'}}
      # on récupère le contenu du dépôt
      - uses: actions/checkout@v3
      - run: ls -la
        if: ${{runner.os == 'linux' || runner.os == 'macos'}}
      - run: dir
        if: ${{runner.os == 'windows'}}
      - name: "Installation de node ${{matrix.version}}x"
        uses: actions/setup-node@v3
        with:
        # on dit d'installer la version 
          node-version: ${{matrix.version}}
      - run: node -v 
      # ${{  }}utilise une variable pour le contexte 
      - run: echo ${{github.actor}} ${{github.event_name}} 
      #Les variables d'env sont passées dans le script
      - run: node dummy.js
        env:
           DATABASE_NAME: 'override du database_name'
      
      - run: pnpm add -D eslint
      - run: pnpm eslint init
      
